name: CI

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 8, 11, 17, 21 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - name: Setup and execute Gradle 'check' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check
    - name: Upload Gradle test reports
      uses: actions/upload-artifact@v3
      with:
        name: gradle_test_reports
        path: build/reports/tests/test
    - name: Test `example` project with Chaos Dukey and confirm it fails
      if: ${{ matrix.java_project == 21 }}
      run: |
        ./gradlew shadowJar &&
        cd example &&
        ln -s ../build/libs/chaos-dukey-*-all.jar chaos-dukey-all.jar &&
        ! ./gradlew test &&
        grep 'expected: &lt;250&gt; but was: &lt;300&gt;' build/reports/tests/test/classes/org.komamitsu.example.jobqueue.JobQueueTest.html
