name: CI

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 8, 11, 17, 21 ]
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Run checks
      run: ./gradlew check
    - name: Upload Gradle test reports
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: gradle_test_reports_java_${{ matrix.java_version }}
        path: build/reports/tests/test
    - name: Test `example` project with Chaos Dukey and confirm it fails
      if: ${{ matrix.java_version == 21 }}
      env:
        CHAOS_DUKEY_ENABLED: true
      run: |
        ./gradlew shadowJar &&
        cd example &&
        ln -s ../build/libs/chaos-dukey-*-all.jar chaos-dukey-all.jar &&
        ! ./gradlew test &&
        grep 'expected: &lt;250&gt; but was: &lt;300&gt;' build/reports/tests/test/classes/org.komamitsu.example.jobqueue.JobQueueTest.html
    - name: Test `example` project without Chaos Dukey and confirm it succeeds
      if: ${{ matrix.java_version == 21 }}
      run: |
        cd example &&
        ./gradlew test
