name: CI

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java_version: 8
            gradle_version: "8.14.4"
          - java_version: 11
            gradle_version: "8.14.4"
          - java_version: 17
            gradle_version: "9.4.1"
          - java_version: 21
            gradle_version: "9.4.1"
          - java_version: 25
            gradle_version: "9.4.1"

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        gradle-version: ${{ matrix.gradle_version }}

    - name: Run checks
      run: gradle check
    - name: Upload Gradle test reports
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: gradle_test_reports_java_${{ matrix.java_version }}
        path: build/reports/tests/test
    - name: Test `example` project with Chaos Dukey and confirm it fails
      if: ${{ matrix.java_version == 21 || matrix.java_version == 25 }}
      env:
        CHAOS_DUKEY_ENABLED: true
      run: |
        gradle shadowJar &&
        cd example &&
        ln -s ../build/libs/chaos-dukey-*-all.jar chaos-dukey-all.jar &&
        ! gradle test &&
        grep -r 'expected: &lt;250&gt; but was: &lt;300&gt;' build/reports/tests/test/
    - name: Test `example` project without Chaos Dukey and confirm it succeeds
      if: ${{ matrix.java_version == 21 || matrix.java_version == 25 }}
      run: |
        cd example &&
        gradle test
